### ISSUE TITLE
Suggestion: Update Android TV icon (image included)

### ISSUE THREAD

**Issue by BrianGilbert** [lubomyr/uae4all2#4]
On my NVidia Shield TV the icon is a picture of a thistle, which is very ambiguous, Here is an image I made using the UAE4All logo..
![uae4all2-logo](https://cloud.githubusercontent.com/assets/114017/14591688/d0cb1e00-0558-11e6-8c09-53cb0a82ec48.png)

**Comment by lubomyr** [comment]
I don't see anything wrong with current icon.
Do you can post screenshot, how it look ?

**Comment by pelya** [comment]
Lubomyr, you need to create image called banner.png inside directory
project/jni/application/uae4all2 , it must be 320x180 image with solid
background.
If you run uae4all2 on Android TV emulator, you'll see the fall-back
flower-themed banner.

**Comment by lubomyr** [comment]
Ok,
Done
